server:
  base_url: "http://localhost:8000"

mapping:
  # (mode, intent) -> gesture
  entries:
    - mode: manipulation
      intent: select_grasp
      gesture: fist
    - mode: manipulation
      intent: release
      gesture: grip1open
